FROM 815684618043.dkr.ecr.us-east-1.amazonaws.com/cruddur-python:3.10-slim-buster
#FROM python:3.10-slim-buster

WORKDIR /backend-flask

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

#ENV FLASK_ENV=development
ENV FLASK_debug=1

EXPOSE ${PORT}
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=4567"]